### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by M165437**
## Changed
- Allow v4 of Symfony component
- Update Robo task runner

### CODE REVIEW

**Comment by M165437** [comment]
Hello Hendrick, I've got an issue with my [API Blueprint Renderer](https://github.com/M165437/laravel-blueprint-docs) supporting the newest version of Laravel as there is a dependency conflict. Laravel 5.6 requires symfony/process v4 while drafter-php only supports v3. In v4 the processBuilder is gone, so I had to rewrite the build method. It's still compatible with v2 and v3 though. What do you think?

**Comment by M165437** [comment]
If you don't mind adding me as a contributor with merge permission to this project as well, I'd be happy to help out. I could also look at the Drafter 4.0.0-pre.0 release over at the reynaldo package if you are busy.

**Comment by M165437** [comment]
Hello Hendrick, when do you think you might have time to look at this?

**Comment by M165437** [comment]
Hello Hendrick, please give me quick feedback on this. Like I said, I'd be happy to help out with this package as well. Thank you!

**Comment by M165437** [comment]
https://www.youtube.com/watch?v=CIxYe3G3Iz4

**Comment by hendrikmaus** [comment]
I am incredibly sorry @M165437 - I completely messed up my notification settings as it seems. I'll fix it right now.

**Comment by M165437** [comment]
Thank you! 🙏☺️

**Comment by dannySanchez1212** [comment]
installing the package I am presented with this error

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: erusev/parsedown[1.7.0, 1.7.1].
    - Can only install one of: erusev/parsedown[1.7.1, 1.7.0].
    - Can only install one of: erusev/parsedown[1.7.0, 1.7.1].
    - m165437/laravel-blueprint-docs v0.4.1 requires erusev/parsedown 1.7.0 -> satisfiable by erusev/parsedown[1.7.0].
    - Installation request for m165437/laravel-blueprint-docs ^0.4.1 -> satisfiable by m165437/laravel-blueprint-docs[v0.4.1].
    - Installation request for erusev/parsedown (locked at 1.7.1, required as ^1.7) -> satisfiable by erusev/parsedown[1.7.1].


Installation failed, reverting ./composer.json to its original content.


ese es mi problema ya instale el paquete que sale del error

Using version ^1.7 for erusev/parsedown
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Discovered Package: nunomaduro/collision
Package manifest generated successfully.

 but still presents the same fault I need to document my api graphically and I think this is the best option

**Comment by M165437** [comment]
@dannySanchez1212 This does not seem to be a problem of drafter-php. Please install the newest version v0.4.2 of [m165437/laravel-blueprint-docs](https://github.com/M165437/laravel-blueprint-docs) which should fix your issue.

**Pull request merged**
